# .github/FUNDING.yml
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [NewTWCM]
# custom: ["https://www.buymeacoffee.com/yourid"] # 如果你有 BuyMeACoffee 可以取消註釋
